pipeline {
    agent {
        docker {
            image 'node:16-alpine'
        }
    }

    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }

        stage('Create a file') {
            steps {
                sh 'touch abc.txt'
            }
        }
    }
}
